Project setup
badger-99/portfolio_v1.0 pull request #1
Opened 2023-04-27 12:07 UTC by badger-99

2023-04-27 12:47 UTC, badger-99 commented on styles.css
> -#kenobi{
I forgot to include changes to this file in the commit message. I made some minor changes to see if they'll pass the Stylelint test, and they did. 

The first change was adding a blank space before the curly-brace on this line.

2023-04-27 12:48 UTC, badger-99 commented on styles.css
> -}
The second change was removing the blank new line after the closing curly-brace.

2023-04-27 12:56 UTC, badger-99 commented on styles.css
> +#kenobi {
I forgot to include changes to this file in the commit message. I made some minor changes to see if they'll pass the Stylelint test, and they did.

The first change was adding a blank space before the opening curly-brace on this line.

2023-04-27 12:57 UTC, badger-99 commented on styles.css
> +}
The second change was removing the blank new line after the closing curly-brace.

2023-04-28 21:36 UTC, Trast00 requested changes
# Require Change ♻️ 
Hi @badger-99 , 

Great job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-reach](https://user-images.githubusercontent.com/74411135/225062441-793da0f4-3ef1-4d98-bee9-9c200c7121a7.gif)

## Highlights
- Project look awsome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

## Required Changes ♻️
_Check the comments under the review._

- Please consider implementing all the change I left below (inline comment).
**(Here is the  [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=yDKg5dMjRcmmZ2y5-0) mentioned in the inline comment)**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 21:36 UTC, Trast00 commented on index.html
> +    </div>
- [ ] Kindly, make sure the logo is in `<a>`, this is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

- [ ] **[OPTIONAL]** Consider using your own logo or your name as the logo. This will make your project more customized 😄

2023-04-28 21:36 UTC, Trast00 commented on index.html
> +    <article id="headline">
- [ ] Please, consider using a `section` tag instead of an `article`. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info This will make your project more semantic 😄

2023-04-28 21:36 UTC, Trast00 commented on index.html
> +        </ul>
- [ ] Please center the content of the texts here to match the figma design. 

**Your project**
![image](https://user-images.githubusercontent.com/74411135/235257825-82dc9f9e-0ac3-4a92-bf37-224557231c33.png)

**Figma design**
![image](https://user-images.githubusercontent.com/74411135/235257880-022a9e04-b50d-4f96-83f3-19f5d4a7767b.png)

This will make your project way more prettier which will improve the user experience 📱  😄 👍

2023-04-28 21:36 UTC, Trast00 commented on index.html
> +      <section id="icon_container">
- [ ] Please do not use a`section` tag here, consider replacing this by a `div`. A section should be used only to separate the main section part of your page ([more info here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)).

This will greatly improve the semantic of your project 😸

2023-04-28 23:45 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @badger-99, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 23:55 UTC, merged